services:

  hospitalization_app:
    build: .
    container_name: hosp
    restart: always
    ports:
      - "8999:8000"
    env_file:
      - .env
    networks:
      - shared_network
    volumes:
      - ./:/app

networks:
  shared_network:
    external: true

 